import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/reset.css";
import "./css/globals.css";
import "./css/variables.css";

import "./css/header.css"
import "./css/navigation.css"
import "./css/main.css"
import "./css/cards.css"

import "./css/responsive.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UFRN - DashBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
